name: Update Release

permissions:
   contents: read

on:
   workflow_dispatch:
   release:
      types: [released]

jobs:
   update-relase-link:
      if: github.repository == 'Fun-Forge-Studio/Cyber'
      runs-on: ubuntu-latest
      steps:
         - name: Trigger update-links workflow on nodejs/release-cloudflare-worker
           run: |
            gh workflow run update-links.yml --repo nodejs/release-cloudflare-worker
           env:
            GITHUB_TOKEN: ${{ secrets.GH_USER_TOKEN }}